#-------------------------------
# General Site Settings
title: Lorrana Melo
logo: logo.svg # You can add own logo.
description: Jornalista de dados e fotógrafa


#-------------------------------
# Author Settings
author:
  name: Lorrana Melo
  image: 01.jpg
  say-hello: <strong>Jornalista de Dados</strong>
  bio: Esse é um texto para <strong>tentar</strong>, <strong>ver</strong>, <strong>se funciona</strong>, a minha ideia sobre o que quero dizer sobre mim! Loves <a href="#">music</a> & riding his bicycle.


#-------------------------------
# Contact links
twitter: https://twitter.com/l0rr4n4_ # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
